# This file was generated by GoReleaser. DO NOT EDIT.
cask "aix" do
  name "aix"
  desc "A tool for managing, creating and sharing agent skills, commands and hooks"
  homepage "https://github.com/thoreinstein/aix"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aix"

  on_macos do
    on_intel do
      url "https://github.com/thoreinstein/aix/releases/download/v#{version}/aix_#{version}_darwin_amd64.tar.gz"
      sha256 "4608f0a189d0ad58044371efa536ec734e063bf060ae5f9e44b88ea8bf5dfed6"
    end
    on_arm do
      url "https://github.com/thoreinstein/aix/releases/download/v#{version}/aix_#{version}_darwin_arm64.tar.gz"
      sha256 "99cdeff2c9048568fb1ef922e91e344660824af537439fe5168f3fdc84134a23"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thoreinstein/aix/releases/download/v#{version}/aix_#{version}_linux_amd64.tar.gz"
      sha256 "b3dab0b7cfaff87c532809e94d0554f229a727c48d7a2893638eed00d3bedd12"
    end
    on_arm do
      url "https://github.com/thoreinstein/aix/releases/download/v#{version}/aix_#{version}_linux_arm64.tar.gz"
      sha256 "de245251b2f28795e0ff011b79bafe57fc82512782ae5d92544a3955b96ed490"
    end
  end

  # No zap stanza required
end
