# This file was generated by GoReleaser. DO NOT EDIT.
cask "aix" do
  name "aix"
  desc "A tool for managing, creating and sharing agent skills, commands and hooks"
  homepage "https://github.com/thoreinstein/aix"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aix"

  on_macos do
    on_intel do
      url "https://github.com/thoreinstein/aix/releases/download/v#{version}/aix_#{version}_darwin_amd64.tar.gz"
      sha256 "2236d4d596adcb0f5482cf051e165d049003211f23f0823726ec686a9a32777d"
    end
    on_arm do
      url "https://github.com/thoreinstein/aix/releases/download/v#{version}/aix_#{version}_darwin_arm64.tar.gz"
      sha256 "0f39cd765c4255171652425ac24f3393a28d19835c21c1b26a86c54a87d72a6c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thoreinstein/aix/releases/download/v#{version}/aix_#{version}_linux_amd64.tar.gz"
      sha256 "c026f6a7a471a24afe758f1507f333a00135f86c7ccac743de35383161c105fa"
    end
    on_arm do
      url "https://github.com/thoreinstein/aix/releases/download/v#{version}/aix_#{version}_linux_arm64.tar.gz"
      sha256 "2be984a2dc28b6bdf11efdad6515654651d1bb07bddaa1659668541355126cad"
    end
  end

  # No zap stanza required
end
