# This file was generated by GoReleaser. DO NOT EDIT.
cask "rig" do
  name "rig"
  desc "Developer workflow automation CLI for Git worktrees, Tmux, and Obsidian integration"
  homepage "https://github.com/thoreinstein/rig"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rig"

  on_macos do
    on_intel do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "6d8009718a7db350407b94240595f1eac1d0fdb0c2a8cc247105a5ed25b51362"
    end
    on_arm do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "754754ca3b075f07e9156d99696d6e1d847110efc052ddbfa9641e4651f56c03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_linux_amd64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "b7d1027df0ed672969c13944c240e639c60faf25c5cea89a9c99f71d116e8874"
    end
    on_arm do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_linux_arm64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "2c4b2fba0016548e59fe4e12867516f8bde3e57dfd3735b75bee96594ccbf402"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rig"]
    end
  end

  # No zap stanza required
end
