# This file was generated by GoReleaser. DO NOT EDIT.
cask "rig" do
  name "rig"
  desc "Developer workflow automation CLI for Git worktrees, Tmux, and Obsidian integration"
  homepage "https://github.com/thoreinstein/rig"
  version "0.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rig"

  on_macos do
    on_intel do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "80ecb20b255481b064338cef69e355c9a4b9e58eb569a85dd9c22d10768ecae6"
    end
    on_arm do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "3e899375a81c36df7a5f43de26dce23e50fa33db846850f6c42def76a8868b6a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_linux_amd64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "6fd35ddfd7e356d6d6d7822dfb18f77e1a9b7d34ede2af8f48a766acf00ffcda"
    end
    on_arm do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_linux_arm64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "f32b300ded583bff51c7ffd99967cb3cad88cc48b27dd57fb2040ba58ad111ab"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rig"]
    end
  end

  # No zap stanza required
end
