# This file was generated by GoReleaser. DO NOT EDIT.
cask "rig" do
  name "rig"
  desc "Developer workflow automation CLI for Git worktrees, Tmux, and Obsidian integration"
  homepage "https://github.com/thoreinstein/rig"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rig"

  on_macos do
    on_intel do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "1f40590977c0e3f5472bd76a2e20036879d358e39a3e312ffa386cdbb4d6fc6d"
    end
    on_arm do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "3cdda659cf82dfe5715de2cbbc8507ea1306366108790acf440368763970ff4f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_linux_amd64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "d16233146960394f9c9701506b2cbc5fa7dd278bc25b81f058fec4422e2ae6f5"
    end
    on_arm do
      url "https://github.com/thoreinstein/rig/releases/download/v#{version}/rig_#{version}_linux_arm64.tar.gz",
        verified: "github.com/thoreinstein/rig/"
      sha256 "875f36e94c0246c86784914f517c47390691725348a07c2a292ce4342ed65d79"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rig"]
    end
  end

  # No zap stanza required
end
