# This file was generated by GoReleaser. DO NOT EDIT.
cask "sre" do
  name "sre"
  desc "SRE workflow automation CLI for Git worktrees, Tmux, and Obsidian integration"
  homepage "https://github.com/thoreinstein/sre"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sre"

  on_macos do
    on_intel do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "ab30e5ed4dc7227c3c66b98e03d32f6c38f1aba3ecdea5dc34dd179e1d7ca19e"
    end
    on_arm do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "39883f3a80f3327e7c8bbabe35470eddc4eb1d42c013cd665288d8c4b6ece8c9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_linux_amd64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "6b616af67987f07a7e6abaf8a4152732ea41d3f8c7b1d745b9c6bad70b40f30b"
    end
    on_arm do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_linux_arm64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "b8f31a5d89f1fea331707eb2163e427e5709d45f29785e1ae2dcdf5278849f45"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sre"]
    end
  end

  # No zap stanza required
end
