# This file was generated by GoReleaser. DO NOT EDIT.
cask "sre" do
  name "sre"
  desc "SRE workflow automation CLI for Git worktrees, Tmux, and Obsidian integration"
  homepage "https://github.com/thoreinstein/sre"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sre"

  on_macos do
    on_intel do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "04e891c53b1c69d2ffb309b5fee3f4a4a5054d1b0baab8d6906537b73acc74fb"
    end
    on_arm do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "47026dad91ceb582368106a9631b9d2b03e7ba1e373646763d41a2dc374e9037"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_linux_amd64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "1ee8510454bb5f6a541752f293e9f2f385df4877b0b1b1bbf26683d11afe2203"
    end
    on_arm do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_linux_arm64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "311e9d1b5902d735fcb4ee8af49d8dc6b93e6cf7cbb72e1b0c56f5019e2204ea"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sre"]
    end
  end

  # No zap stanza required
end
