# This file was generated by GoReleaser. DO NOT EDIT.
cask "sre" do
  name "sre"
  desc "SRE workflow automation CLI for Git worktrees, Tmux, and Obsidian integration"
  homepage "https://github.com/thoreinstein/sre"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sre"

  on_macos do
    on_intel do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "76c0a3436308874124be93e69ad7008e6f8853e94983a9900df7058a3e997933"
    end
    on_arm do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "6b5a7c94ef8c5830e02b8dcf9726c73b7575d096d8943c98594ecd4992bbf2bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_linux_amd64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "b6a815e7c78644911990e2db9907088d38d7b85c8624c6b19594e294922a98aa"
    end
    on_arm do
      url "https://github.com/thoreinstein/sre/releases/download/v#{version}/sre_#{version}_linux_arm64.tar.gz",
        verified: "github.com/thoreinstein/sre/"
      sha256 "90aefe6250f53095f73405a0eaadd7c8a62e4238101dd5d6b5c544722edcebb1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sre"]
    end
  end

  # No zap stanza required
end
